/* A recursive-descent parser generated by greg 0.4.3 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct _GREG;
#define YYRULECOUNT 18

#include <stdio.h>
#include "ast.h"
#include "symbol.h"
#include "exception.h"

static int eat_eol = 0;

#define YYSTYPE ast_t *

/* 
   Increase the parse buffers
*/

#define YY_BUFFER_START_SIZE 16384 

#define YY_STACK_SIZE YY_BUFFER_START_SIZE

#define YY_INPUT(buf, result, max_size, core)          \
{                                                      \
  int yyc = fgetc(stdin);                              \
  if (yyc == EOF) { eat_eol = 0; longjmp(exc, 2); }    \
  if (eat_eol) while (yyc == '\n') yyc = fgetc(stdin); \
  if (yyc == '(') eat_eol++;                           \
  if (yyc == ')') eat_eol--;                           \
  result = (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
}

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)     static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)    static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)      static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)     T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size, D)              \
  {                                                     \
    int yyc= getchar();                                 \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yyprintf((stderr, "<%c>", yyc));                  \
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN        ( yytextpos= G->begin= G->pos, 1)
#endif
#ifndef YY_END
#define YY_END          ( G->end= G->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args) fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE int
#endif
#ifndef YY_XTYPE
#define YY_XTYPE void *
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 1024
#endif

#ifndef YY_PART
#define yydata G->data
#define yy G->ss

struct _yythunk; // forward declaration
typedef void (*yyaction)(struct _GREG *G, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

typedef struct _GREG {
  char *buf;
  int buflen;
  int   offset;
  int   pos;
  int   limit;
  char *text;
  int   textlen;
  int   begin;
  int   end;
  yythunk *thunks;
  int   thunkslen;
  int thunkpos;
  YYSTYPE ss;
  YYSTYPE *val;
  YYSTYPE *vals;
  int valslen;
  YY_XTYPE data;
} GREG;

YY_LOCAL(int) yyrefill(GREG *G)
{
  int yyn;
  while (G->buflen - G->pos < 512)
    {
      G->buflen *= 2;
      G->buf= (char*)YY_REALLOC(G->buf, G->buflen, G->data);
    }
  YY_INPUT((G->buf + G->pos), yyn, (G->buflen - G->pos), G->data);
  if (!yyn) return 0;
  G->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *G)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  ++G->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(GREG *G, int c)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  if ((unsigned char)G->buf[G->pos] == c)
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *G, const char *s)
{
  int yysav= G->pos;
  while (*s)
    {
      if (G->pos >= G->limit && !yyrefill(G)) return 0;
      if (G->buf[G->pos] != *s)
        {
          G->pos= yysav;
          return 0;
        }
      ++s;
      ++G->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *G, unsigned char *bits)
{
  int c;
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  c= (unsigned char)G->buf[G->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", G->buf+G->pos));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *G, yyaction action, int begin, int end)
{
  while (G->thunkpos >= G->thunkslen)
    {
      G->thunkslen *= 2;
      G->thunks= (yythunk*)YY_REALLOC(G->thunks, sizeof(yythunk) * G->thunkslen, G->data);
    }
  G->thunks[G->thunkpos].begin=  begin;
  G->thunks[G->thunkpos].end=    end;
  G->thunks[G->thunkpos].action= action;
  ++G->thunkpos;
}

YY_LOCAL(int) yyText(GREG *G, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (G->textlen < (yyleng - 1))
        {
          G->textlen *= 2;
          G->text= (char*)YY_REALLOC(G->text, G->textlen, G->data);
        }
      memcpy(G->text, G->buf + begin, yyleng);
    }
  G->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *G)
{
  int pos;
  for (pos= 0; pos < G->thunkpos; ++pos)
    {
      yythunk *thunk= &G->thunks[pos];
      int yyleng= thunk->end ? yyText(G, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, G->text));
      thunk->action(G, G->text, yyleng, thunk, G->data);
    }
  G->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *G)
{
  if ((G->limit -= G->pos))
    {
      memmove(G->buf, G->buf + G->pos, G->limit);
    }
  G->offset += G->pos;
  G->begin -= G->pos;
  G->end -= G->pos;
  G->pos= G->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *G, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(G);
      yyCommit(G);
    }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) { G->val += count; }
YY_LOCAL(void) yyPop(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val -= count; }
YY_LOCAL(void) yySet(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val[count]= G->ss; }

#endif /* YY_PART */

#define YYACCEPT        yyAccept(G, yythunkpos0)

YY_RULE(int) yy_Sp2(GREG *G); /* 18 */
YY_RULE(int) yy_Comment(GREG *G); /* 17 */
YY_RULE(int) yy_Space(GREG *G); /* 16 */
YY_RULE(int) yy_RParen(GREG *G); /* 15 */
YY_RULE(int) yy_LParen(GREG *G); /* 14 */
YY_RULE(int) yy_Integer(GREG *G); /* 13 */
YY_RULE(int) yy_Mod(GREG *G); /* 12 */
YY_RULE(int) yy_Div(GREG *G); /* 11 */
YY_RULE(int) yy_Times(GREG *G); /* 10 */
YY_RULE(int) yy_Primary(GREG *G); /* 9 */
YY_RULE(int) yy_Minus(GREG *G); /* 8 */
YY_RULE(int) yy_Plus(GREG *G); /* 7 */
YY_RULE(int) yy_Infix10(GREG *G); /* 6 */
YY_RULE(int) yy_Expression(GREG *G); /* 5 */
YY_RULE(int) yy_EOL(GREG *G); /* 4 */
YY_RULE(int) yy_Statement(GREG *G); /* 3 */
YY_RULE(int) yy_Spacing(GREG *G); /* 2 */
YY_RULE(int) yy_start(GREG *G); /* 1 */

YY_ACTION(void) yy_1_Integer(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Integer\n"));
  
                 sym_t * sym = sym_lookup(yytext);
                 yy = ast_symbol(T_INT, sym);
              ;
}
YY_ACTION(void) yy_4_Infix10(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_4_Infix10\n"));
   yy = r; ;
#undef s
#undef r
}
YY_ACTION(void) yy_3_Infix10(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_3_Infix10\n"));
   r = ast_binop(sym_lookup("%"), r, s); ;
#undef s
#undef r
}
YY_ACTION(void) yy_2_Infix10(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_2_Infix10\n"));
   r = ast_binop(sym_lookup("/"), r, s); ;
#undef s
#undef r
}
YY_ACTION(void) yy_1_Infix10(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_1_Infix10\n"));
   r = ast_binop(sym_lookup("*"), r, s); ;
#undef s
#undef r
}
YY_ACTION(void) yy_3_Expression(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_3_Expression\n"));
   yy = r; ;
#undef s
#undef r
}
YY_ACTION(void) yy_2_Expression(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_2_Expression\n"));
   r = ast_binop(sym_lookup("-"), r, s); ;
#undef s
#undef r
}
YY_ACTION(void) yy_1_Expression(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_1_Expression\n"));
   r = ast_binop(sym_lookup("+"), r, s); ;
#undef s
#undef r
}
YY_ACTION(void) yy_2_start(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_2_start\n"));
   root = NULL; eat_eol = 0; printf("Syntax error\n"); ;
#undef r
}
YY_ACTION(void) yy_1_start(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_1_start\n"));
   root = r; ;
#undef r
}

YY_RULE(int) yy_Sp2(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;

  yyprintf((stderr, "%s\n", "Sp2"));
  l2:;	
  {  int yypos3= G->pos, yythunkpos3= G->thunkpos;
  {  int yypos4= G->pos, yythunkpos4= G->thunkpos;  if (!yy_Space(G)) { goto l5; }  goto l4;
  l5:;	  G->pos= yypos4; G->thunkpos= yythunkpos4;  if (!yy_EOL(G)) { goto l6; }  goto l4;
  l6:;	  G->pos= yypos4; G->thunkpos= yythunkpos4;  if (!yy_Comment(G)) { goto l3; }
  }
  l4:;	  goto l2;
  l3:;	  G->pos= yypos3; G->thunkpos= yythunkpos3;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Sp2", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_Comment(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Comment"));  if (!yymatchString(G, "/*")) goto l7;
  l8:;	
  {  int yypos9= G->pos, yythunkpos9= G->thunkpos;
  {  int yypos10= G->pos, yythunkpos10= G->thunkpos;  if (!yymatchString(G, "*/")) goto l10;  goto l9;
  l10:;	  G->pos= yypos10; G->thunkpos= yythunkpos10;
  }  if (!yymatchDot(G)) goto l9;  goto l8;
  l9:;	  G->pos= yypos9; G->thunkpos= yythunkpos9;
  }  if (!yymatchString(G, "*/")) goto l7;
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", G->buf+G->pos));
  return 1;
  l7:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Space(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Space"));
  {  int yypos12= G->pos, yythunkpos12= G->thunkpos;  if (!yymatchChar(G, ' ')) goto l13;  goto l12;
  l13:;	  G->pos= yypos12; G->thunkpos= yythunkpos12;  if (!yymatchChar(G, '\t')) goto l11;
  }
  l12:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", G->buf+G->pos));
  return 1;
  l11:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Space", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_RParen(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "RParen"));  if (!yymatchChar(G, ')')) goto l14;  if (!yy_Spacing(G)) { goto l14; }
  yyprintf((stderr, "  ok   %s @ %s\n", "RParen", G->buf+G->pos));
  return 1;
  l14:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RParen", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LParen(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LParen"));  if (!yymatchChar(G, '(')) goto l15;  if (!yy_Spacing(G)) { goto l15; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LParen", G->buf+G->pos));
  return 1;
  l15:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LParen", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Integer(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Integer"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l16;
  {  int yypos17= G->pos, yythunkpos17= G->thunkpos;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l18;
  l19:;	
  {  int yypos20= G->pos, yythunkpos20= G->thunkpos;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l20;  goto l19;
  l20:;	  G->pos= yypos20; G->thunkpos= yythunkpos20;
  }  goto l17;
  l18:;	  G->pos= yypos17; G->thunkpos= yythunkpos17;  if (!yymatchChar(G, '0')) goto l16;
  }
  l17:;	  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l16;  if (!yy_Spacing(G)) { goto l16; }  yyDo(G, yy_1_Integer, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Integer", G->buf+G->pos));
  return 1;
  l16:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Integer", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Mod(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Mod"));  if (!yymatchChar(G, '%')) goto l21;  if (!yy_Sp2(G)) { goto l21; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Mod", G->buf+G->pos));
  return 1;
  l21:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Mod", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Div(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Div"));  if (!yymatchChar(G, '/')) goto l22;  if (!yy_Sp2(G)) { goto l22; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Div", G->buf+G->pos));
  return 1;
  l22:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Div", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Times(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Times"));  if (!yymatchChar(G, '*')) goto l23;  if (!yy_Sp2(G)) { goto l23; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Times", G->buf+G->pos));
  return 1;
  l23:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Times", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Primary(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Primary"));
  {  int yypos25= G->pos, yythunkpos25= G->thunkpos;  if (!yy_Integer(G)) { goto l26; }  goto l25;
  l26:;	  G->pos= yypos25; G->thunkpos= yythunkpos25;  if (!yy_LParen(G)) { goto l24; }  if (!yy_Expression(G)) { goto l24; }  if (!yy_RParen(G)) { goto l24; }
  }
  l25:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Primary", G->buf+G->pos));
  return 1;
  l24:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Primary", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Minus(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Minus"));  if (!yymatchChar(G, '-')) goto l27;  if (!yy_Sp2(G)) { goto l27; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Minus", G->buf+G->pos));
  return 1;
  l27:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Minus", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Plus(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Plus"));  if (!yymatchChar(G, '+')) goto l28;  if (!yy_Sp2(G)) { goto l28; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Plus", G->buf+G->pos));
  return 1;
  l28:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Plus", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix10(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Infix10"));  if (!yy_Primary(G)) { goto l29; }  yyDo(G, yySet, -2, 0);
  l30:;	
  {  int yypos31= G->pos, yythunkpos31= G->thunkpos;
  {  int yypos32= G->pos, yythunkpos32= G->thunkpos;  if (!yy_Times(G)) { goto l33; }  if (!yy_Primary(G)) { goto l33; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_Infix10, yytextpos?yytextpos:G->begin, G->end);  goto l32;
  l33:;	  G->pos= yypos32; G->thunkpos= yythunkpos32;  if (!yy_Div(G)) { goto l34; }  if (!yy_Primary(G)) { goto l34; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_2_Infix10, yytextpos?yytextpos:G->begin, G->end);  goto l32;
  l34:;	  G->pos= yypos32; G->thunkpos= yythunkpos32;  if (!yy_Mod(G)) { goto l31; }  if (!yy_Primary(G)) { goto l31; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_3_Infix10, yytextpos?yytextpos:G->begin, G->end);
  }
  l32:;	  goto l30;
  l31:;	  G->pos= yypos31; G->thunkpos= yythunkpos31;
  }  yyDo(G, yy_4_Infix10, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix10", G->buf+G->pos));  yyDo(G, yyPop, 2, 0);
  return 1;
  l29:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix10", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Expression(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Expression"));  if (!yy_Infix10(G)) { goto l35; }  yyDo(G, yySet, -2, 0);
  l36:;	
  {  int yypos37= G->pos, yythunkpos37= G->thunkpos;
  {  int yypos38= G->pos, yythunkpos38= G->thunkpos;  if (!yy_Plus(G)) { goto l39; }  if (!yy_Infix10(G)) { goto l39; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_Expression, yytextpos?yytextpos:G->begin, G->end);  goto l38;
  l39:;	  G->pos= yypos38; G->thunkpos= yythunkpos38;  if (!yy_Minus(G)) { goto l37; }  if (!yy_Infix10(G)) { goto l37; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_2_Expression, yytextpos?yytextpos:G->begin, G->end);
  }
  l38:;	  goto l36;
  l37:;	  G->pos= yypos37; G->thunkpos= yythunkpos37;
  }  yyDo(G, yy_3_Expression, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Expression", G->buf+G->pos));  yyDo(G, yyPop, 2, 0);
  return 1;
  l35:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expression", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_EOL(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos41= G->pos, yythunkpos41= G->thunkpos;  if (!yymatchString(G, "\r\n")) goto l42;  goto l41;
  l42:;	  G->pos= yypos41; G->thunkpos= yythunkpos41;  if (!yymatchChar(G, '\n')) goto l43;  goto l41;
  l43:;	  G->pos= yypos41; G->thunkpos= yythunkpos41;  if (!yymatchChar(G, '\r')) goto l40;
  }
  l41:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", G->buf+G->pos));
  return 1;
  l40:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Statement(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Statement"));
  {  int yypos45= G->pos, yythunkpos45= G->thunkpos;  if (!yy_Spacing(G)) { goto l46; }  if (!yy_Expression(G)) { goto l46; }  if (!yy_EOL(G)) { goto l46; }  goto l45;
  l46:;	  G->pos= yypos45; G->thunkpos= yythunkpos45;  if (!yy_Spacing(G)) { goto l44; }  if (!yy_EOL(G)) { goto l44; }
  }
  l45:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Statement", G->buf+G->pos));
  return 1;
  l44:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Statement", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Spacing(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;

  yyprintf((stderr, "%s\n", "Spacing"));
  l48:;	
  {  int yypos49= G->pos, yythunkpos49= G->thunkpos;
  {  int yypos50= G->pos, yythunkpos50= G->thunkpos;  if (!yy_Space(G)) { goto l51; }  goto l50;
  l51:;	  G->pos= yypos50; G->thunkpos= yythunkpos50;  if (!yy_Comment(G)) { goto l49; }
  }
  l50:;	  goto l48;
  l49:;	  G->pos= yypos49; G->thunkpos= yythunkpos49;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Spacing", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_start(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos53= G->pos, yythunkpos53= G->thunkpos;  if (!yy_Spacing(G)) { goto l54; }  if (!yy_Statement(G)) { goto l54; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_start, yytextpos?yytextpos:G->begin, G->end);  goto l53;
  l54:;	  G->pos= yypos53; G->thunkpos= yythunkpos53;
  l55:;	
  {  int yypos56= G->pos, yythunkpos56= G->thunkpos;
  {  int yypos57= G->pos, yythunkpos57= G->thunkpos;  if (!yy_EOL(G)) { goto l57; }  goto l56;
  l57:;	  G->pos= yypos57; G->thunkpos= yythunkpos57;
  }  if (!yymatchDot(G)) goto l56;  goto l55;
  l56:;	  G->pos= yypos56; G->thunkpos= yythunkpos56;
  }  if (!yy_EOL(G)) { goto l52; }  yyDo(G, yy_2_start, yytextpos?yytextpos:G->begin, G->end);
  }
  l53:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", G->buf+G->pos));  yyDo(G, yyPop, 1, 0);
  return 1;
  l52:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", G->buf+G->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *G);

YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)
{
  int yyok;
  if (!G->buflen)
    {
      G->buflen= YY_BUFFER_START_SIZE;
      G->buf= (char*)YY_ALLOC(G->buflen, G->data);
      G->textlen= YY_BUFFER_START_SIZE;
      G->text= (char*)YY_ALLOC(G->textlen, G->data);
      G->thunkslen= YY_STACK_SIZE;
      G->thunks= (yythunk*)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);
      G->valslen= YY_STACK_SIZE;
      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);
      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;
    }
  G->pos = 0;
  G->begin= G->end= G->pos;
  G->thunkpos= 0;
  G->val= G->vals;
  yyok= yystart(G);
  if (yyok) yyDone(G);
  yyCommit(G);
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
}

YY_PARSE(int) YY_NAME(parse)(GREG *G)
{
  return YY_NAME(parse_from)(G, yy_start);
}

YY_PARSE(void) YY_NAME(init)(GREG *G)
{
    memset(G, 0, sizeof(GREG));
}
YY_PARSE(void) YY_NAME(deinit)(GREG *G)
{
    if (G->buf) YY_FREE(G->buf);
    if (G->text) YY_FREE(G->text);
    if (G->thunks) YY_FREE(G->thunks);
    if (G->vals) YY_FREE(G->vals);
}
YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *G = (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);
  G->data = data;
  return G;
}

YY_PARSE(void) YY_NAME(parse_free)(GREG *G)
{
  YY_NAME(deinit)(G);
  YY_FREE(G);
}

#endif
